version: '3.8'

services:
  crypto-web:
    working_dir: /app
    build: ./client/crypto-web
    volumes:
      - ./client/crypto-web:/app
    image: node:15.3.0-alpine3.12
    environment:
      PORT: 5000
      PROXY_API_URL: http://bet-service:3000
    entrypoint: 'npm run dev'
    links:
      - 'bet-service'
    ports:
      - "5000:5000"

  bet-service:
    working_dir: /app
    env_file:
      "./services/bet/.env"
    build:
      context: ./services/bet
    volumes:
      - ./services/bet:/app
    image: node:15.3.0-alpine3.12
    entrypoint: 'npm start'
    ports:
      - "3000:3000"
