name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/bet
    env:
      READING_HMAC_SECRET: ${{secrets.READING_HMAC_SECRET}}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test 
       
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: eu-west-2
          application_name: CryptoWizard
          environment_name: crypto-wizard-staging
          version_label: ${GITHUB_SHA::8}
          deployment_package: deploy.zip
