name: cd-services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/bet
    env:
      READING_HMAC_SECRET: ${{secrets.READING_HMAC_SECRET}}
      GITSHA: $(git rev-parse --short HEAD)

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - run: echo ${{ env.GITSHA }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test 
       
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' -x "**node_modules**"


      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: eu-west-2
          application_name: CryptoWizard
          environment_name: crypto-wizard-staging
          version_label: ${{ env.GITSHA }}
          deployment_package: ./services/bet/deploy.zip
          
      - name: Deployed!
        run: echo App deployed to ELB          
